import type { Metadata } from 'next'
import '@/styles/globals.scss'
import SiteHeader from '@/components/organisms/SiteHeader'
import { LenisProvider } from '@/components/providers/LenisProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <LenisProvider>
          <SiteHeader />
          {children}
        </LenisProvider>
      </body>
    </html>
  )
}
